version: '3'

services:
  node-1:
    build: .
    networks:
      default:
        ipv4_address: 10.0.1.1
    # ports:
      # - "4444:4444"    
    
  
  node-2:
    build: .
    networks:
      default:
        ipv4_address: 10.0.1.2
    # ports:
      # - "4444:4444"

  node-3:
    build: .
    networks:
      default:
        ipv4_address: 10.0.1.3
    # ports:
      # - "4444:4444"

  node-4:
    build: .
    networks:
      default:
        ipv4_address: 10.0.1.4
    # ports:
      # - "4444:4444"

  node-5:
    build: .
    networks:
      default:
        ipv4_address: 10.0.1.5
    # ports:
      # - "4444:4444"


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.254
